;;; majjic-tests.el --- Lightweight tests for Majjic -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;;; Commentary:

;; Small seam-focused tests for the Majjic refactor.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'majjic)

(defun majjic-test--kill-demo-buffer ()
  "Remove any existing demo log buffer so tests start with clean UI state."
  (when-let* ((buffer (get-buffer "majjic: majjic-demo")))
    (kill-buffer buffer)))

(ert-deftest majjic-test-parse-root-and-trailing-elided ()
  "Root revisions should not synthesize a summary, and trailing `~' survives."
  (let* ((sep majjic--record-separator)
         (output (concat sep "zzzzzzzz" sep "00000000" sep "◆ zzzzzzzz root() 00000000\n"
                         "│\n"
                         "~\n"))
         (records (majjic--parse-log-output output)))
    (should (= (length records) 2))
    (should (eq (majjic-revision-kind (nth 0 records)) 'revision))
    (should-not (majjic-revision-summary (nth 0 records)))
    (should (eq (majjic-revision-kind (nth 1 records)) 'graph))
    (should (equal (majjic-revision-heading (nth 1 records)) "~"))))

(ert-deftest majjic-test-parse-summary-and-multi-hunk-diff ()
  "Summary parsing should preserve rename rows and parse multiple hunks."
  (let* ((changes (majjic--parse-file-summary-output
                   "M app.py\nR {old.txt => new.txt}"))
         (hunks (majjic--parse-file-diff-output
                 (string-join
                  '("diff --git a/app.py b/app.py"
                    "index 1111111..2222222 100644"
                    "--- a/app.py"
                    "+++ b/app.py"
                    "@@ -1,2 +1,2 @@"
                    "-old"
                    "+new"
                    "@@ -10 +10 @@"
                    "-x"
                    "+y")
                  "\n"))))
    (should (= (length changes) 2))
    (should (equal (majjic-file-change-path (nth 0 changes)) "app.py"))
    (should (majjic-file-change-rename (nth 1 changes)))
    (should (= (length hunks) 2))
    (should (= (majjic-hunk-index (nth 0 hunks)) 0))
    (should (= (majjic-hunk-index (nth 1 hunks)) 1))
    (should (= (majjic-hunk-old-start (nth 1 hunks)) 10))
    (should (= (majjic-hunk-new-start (nth 1 hunks)) 10))))

(ert-deftest majjic-test-refresh-preserves-selection-and-expansion ()
  "A rerender should preserve the selected revision and expanded revision state."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (goto-char (point-min))
      (let ((top-prefix (majjic--rebase-target-summary-prefix
                         (majjic--current-revision-section) 'after)))
        (should-not (string-match-p "│" top-prefix)))
      (goto-char (point-min))
      (should (search-forward "Edit notes in two distant hunks" nil t))
      (beginning-of-line)
      (let ((selected (majjic--current-commit-id)))
        (majjic-toggle-at-point)
        (should (= (length (majjic--expanded-commit-ids)) 1))
        (majjic--log-refresh-sync (majjic--capture-refresh-state))
        (should (equal (majjic--current-commit-id) selected))
        (should (= (length (majjic--expanded-commit-ids)) 1))))))

(ert-deftest majjic-test-current-row-ids-are-explicitly-split ()
  "Current-row state should use commit ids, with change ids stored as section metadata."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (goto-char (point-min))
      (should (search-forward "Edit notes in two distant hunks" nil t))
      (beginning-of-line)
      (let* ((section (majjic--current-revision-section))
             (commit-id (majjic--current-commit-id))
             (change-id (oref section change-id)))
        (should (equal commit-id (oref section value)))
        (should (equal change-id (majjic--change-id-for-commit-id commit-id)))
        (should-not (equal commit-id change-id))
        (should (majjic--revision-section-moved-p section (list change-id)))))))

(ert-deftest majjic-test-marks-persist-and-seed-transient-modes ()
  "Persistent marks should survive refresh and seed abandon/rebase entry."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (goto-char (point-min))
      (should (search-forward "Edit notes in two distant hunks" nil t))
      (beginning-of-line)
      (majjic-section-up)
      (let* ((marked-section (majjic--current-revision-section))
             (marked-change-id (oref marked-section change-id))
             (marked-commit-id (oref marked-section value))
             (marked-section-start (marker-position (oref marked-section start))))
        (should (eq (key-binding (kbd "SPC")) #'majjic-space))
        (majjic-space)
        (should (equal majjic--marked-change-ids (list marked-change-id)))
        (should-not (equal (majjic--current-commit-id) marked-commit-id))
        (should (seq-some (lambda (overlay)
                            (and (overlay-start overlay)
                                 (equal (overlay-get overlay 'majjic-mark-change-id)
                                        marked-change-id)
                                 (= (overlay-start overlay) marked-section-start)
                                 (equal (get-text-property 0 'face (overlay-get overlay 'display))
                                        'majjic-marked-row)))
                          majjic--mark-overlays))
        (magit-section-goto marked-section)
        (majjic--sync-mark-overlays)
        (should (seq-some (lambda (overlay)
                            (and (equal (overlay-get overlay 'majjic-mark-change-id)
                                        marked-change-id)
                                 (equal (get-text-property 0 'face (overlay-get overlay 'display))
                                        '(:inherit (majjic-marked-row magit-section-highlight)))))
                          majjic--mark-overlays))
        (majjic-toggle-at-point)
        (majjic-section-forward)
        (let ((child-commit-id (majjic--current-commit-id)))
          (majjic-space)
          (should (equal (majjic--current-commit-id) child-commit-id))
          (should-not (member marked-change-id majjic--marked-change-ids))
          (majjic-space)
          (should (equal (majjic--current-commit-id) child-commit-id))
          (should (member marked-change-id majjic--marked-change-ids)))
        (majjic--sync-mark-overlays)
        (should (seq-some (lambda (overlay)
                            (and (equal (overlay-get overlay 'majjic-mark-change-id)
                                        marked-change-id)
                                 (equal (get-text-property 0 'face (overlay-get overlay 'display))
                                        'majjic-marked-row)))
                          majjic--mark-overlays))
        (magit-section-goto marked-section)
        (majjic--log-refresh-sync (majjic--capture-refresh-state))
        (should (equal majjic--marked-change-ids (list marked-change-id)))
        (should (seq-some (lambda (overlay)
                            (equal (overlay-get overlay 'majjic-mark-change-id)
                                   marked-change-id))
                          majjic--mark-overlays))
        (cl-letf* ((prompted nil)
                   (saw-overlay nil)
                   (saw-mark-overlay nil)
                   ((symbol-function 'y-or-n-p)
                    (lambda (_prompt)
                      (setq prompted t)
                      (setq saw-overlay
                            (seq-some (lambda (overlay)
                                        (equal (overlay-get overlay 'majjic-abandon-commit-id)
                                               marked-commit-id))
                                      majjic--abandon-overlays))
                      (setq saw-mark-overlay majjic--mark-overlays)
                      nil)))
          (majjic-abandon-start)
          (should prompted)
          (should saw-overlay)
          (should-not saw-mark-overlay))
        (should-not majjic--abandon-overlays)
        (should-not majjic--abandon-selected-commit-ids)
        (should (equal majjic--marked-change-ids (list marked-change-id)))
        (should (seq-some (lambda (overlay)
                            (equal (overlay-get overlay 'majjic-mark-change-id)
                                   marked-change-id))
                          majjic--mark-overlays))
        (majjic-rebase-start)
        (should (equal (majjic-rebase-state-source-change-id majjic--rebase-state)
                       marked-change-id))
        (goto-char (point-min))
        (let ((top-change-id (oref (majjic--current-revision-section) change-id)))
          (majjic-toggle-mark)
          (should (equal (majjic-rebase-state-source-change-id majjic--rebase-state)
                         (majjic--marked-visible-change-ids)))
          (should (member top-change-id (majjic--rebase-source-change-ids
                                         (majjic-rebase-state-source-change-id majjic--rebase-state)))))
        (majjic-rebase-cancel)
        (should (member marked-change-id majjic--marked-change-ids))
        (majjic-clear-marks)
        (should-not majjic--marked-change-ids)
        (should-not majjic--mark-overlays)))))

(ert-deftest majjic-test-reserved-browser-keybindings-exist ()
  "Top-level browser keybindings should be reserved in the main log."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (should (eq (key-binding "O") #'majjic-op-log-browser))
      (should (eq (key-binding "B") #'majjic-bookmark-browser))
      (should-error (call-interactively #'majjic-op-log-browser) :type 'user-error)
      (should-error (call-interactively #'majjic-bookmark-browser) :type 'user-error))))

(ert-deftest majjic-test-rebase-command-args ()
  "Rebase command args should map target modes to the expected jj flags."
  (should (equal (majjic--rebase-args "src" "dst" 'onto)
                 '("rebase" "--revisions" "src" "--onto" "dst")))
  (should (equal (majjic--rebase-args "src" "dst" 'after)
                 '("rebase" "--revisions" "src" "--insert-after" "dst")))
  (should (equal (majjic--rebase-args "src" "dst" 'before)
                 '("rebase" "--revisions" "src" "--insert-before" "dst")))
  (should (equal (majjic--rebase-args "src" "dst" 'onto 'descendants)
                 '("rebase" "--source" "src" "--onto" "dst")))
  (should (equal (majjic--rebase-args '("src1" "src2") "dst" 'onto)
                 '("rebase" "--revisions" "src1" "--revisions" "src2" "--onto" "dst"))))

(ert-deftest majjic-test-new-uses-marked-revisions-when-present ()
  "`majjic-new' should use visible marked revisions as parents when present."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (let* ((revisions (seq-filter (lambda (child)
                                      (object-of-class-p child 'majjic-revision-section))
                                    (oref magit-root-section children)))
             (parents (mapcar (lambda (revision) (oref revision value))
                              (seq-take revisions 2)))
             (majjic--marked-change-ids (mapcar (lambda (revision) (oref revision change-id))
                                                (seq-take revisions 2)))
             (called nil))
        (cl-letf (((symbol-function 'majjic--run-mutation)
                   (lambda (thunk &rest _args) (funcall thunk)))
                  ((symbol-function 'majjic--call-jj)
                   (lambda (_repo &rest args)
                     (setq called args)
                     "")))
          (majjic-new))
        (should (equal called (cons "new" parents)))))))

(ert-deftest majjic-test-undo-redo-command-args ()
  "Undo and redo helpers should return the expected jj command shapes."
  (should (equal (majjic--undo-args) '("undo")))
  (should (equal (majjic--redo-args) '("redo")))
  (let ((majjic--repo-root "/tmp")
        (called nil))
    (cl-letf (((symbol-function 'majjic--call-jj)
               (lambda (_dir &rest args)
                 (setq called args)
                 "op-summary\n")))
      (should (equal (majjic--op-log-preview) "op-summary"))
      (should (equal called '("--at-op" "@" "--ignore-working-copy"
                              "op" "log" "-n" "1" "--color" "always"
                              "--no-pager"))))))

(ert-deftest majjic-test-op-preview-buffer-renders-ansi-colors ()
  "The temporary operation preview buffer should render ANSI faces, not escapes."
  (let ((buffer (get-buffer-create "*majjic test preview*")))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'majjic--op-log-preview)
                     (lambda ()
                       "\e[31mred op\e[0m\nplain")))
            (majjic--prepare-op-preview-buffer buffer (majjic--op-log-preview)))
          (with-current-buffer buffer
            (should (equal (buffer-string) "red op\nplain\n"))
            (should-not (string-match-p "\e\\[" (buffer-string)))
            (should (seq-some (lambda (overlay)
                                (overlay-get overlay 'face))
                              (overlays-at (point-min))))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer)))))

(ert-deftest majjic-test-confirm-latest-operation-peek-cleans-up-on-decline ()
  "Declining confirmation should close and kill the temporary side-window peek."
  (save-window-excursion
    (let ((selected (selected-window))
          (display-called nil)
          (original-display (symbol-function 'display-buffer-in-side-window)))
      (unwind-protect
          (progn
            (cl-letf (((symbol-function 'majjic--effective-undo-operation-preview)
                       (lambda ()
                         "@  abc user 1 minute ago\n│  new empty commit"))
                      ((symbol-function 'display-buffer-in-side-window)
                       (lambda (buffer alist)
                         (setq display-called (list buffer alist))
                         (funcall original-display buffer alist)))
                      ((symbol-function 'y-or-n-p)
                       (lambda (_prompt)
                         (should (equal (selected-window) selected))
                         (should (get-buffer-window "*majjic undo preview*"))
                         nil)))
              (should-not (majjic--confirm-latest-operation "undo")))
            (should display-called)
            (should (equal (alist-get 'side (cadr display-called)) 'bottom))
            (should-not (get-buffer "*majjic undo preview*")))
        (when-let* ((buffer (get-buffer "*majjic undo preview*")))
          (kill-buffer buffer))))))

(ert-deftest majjic-test-confirm-latest-operation-peek-cleans-up-on-quit ()
  "`C-g' during confirmation should also clean up the temporary peek."
  (cl-letf (((symbol-function 'majjic--effective-redo-operation-preview)
             (lambda ()
               "@  abc user 1 minute ago\n│  new empty commit"))
            ((symbol-function 'y-or-n-p)
             (lambda (_prompt)
               (keyboard-quit))))
    (let ((quit-seen nil))
      (save-window-excursion
        (condition-case nil
            (majjic--confirm-latest-operation "redo")
          (quit (setq quit-seen t))))
      (should quit-seen))
    (should-not (get-buffer "*majjic redo preview*"))))

(ert-deftest majjic-test-confirm-latest-operation-fetches-preview-in-log-buffer ()
  "Fetching op-log preview should happen before switching to the temporary buffer."
  (with-temp-buffer
    (let ((majjic--repo-root "/repo")
          (called-root nil))
      (cl-letf (((symbol-function 'majjic--effective-undo-operation-preview)
                 (lambda ()
                   (setq called-root majjic--repo-root)
                   "latest op"))
                ((symbol-function 'display-buffer-in-side-window)
                 (lambda (&rest _args)
                   (selected-window)))
                ((symbol-function 'y-or-n-p)
                 (lambda (_prompt) nil)))
        (should-not (majjic--confirm-latest-operation "undo"))
        (should (equal called-root "/repo"))))))

(ert-deftest majjic-test-prompts-for-directory-outside-repo ()
  "Opening `majjic' outside a repo should prompt for a directory first."
  (let* ((start-dir (file-name-as-directory (make-temp-file "majjic-start-" t)))
         (picked-dir (file-name-as-directory (make-temp-file "majjic-picked-" t)))
         (buffer-name (majjic--log-buffer-name picked-dir))
         (prompted nil)
         (opened-root nil)
         (opened-default-directory nil))
    (unwind-protect
        (let ((default-directory start-dir))
          (cl-letf (((symbol-function 'majjic--locate-root)
                     (lambda (dir)
                       (cond
                        ((equal dir start-dir) nil)
                        ((equal dir picked-dir) picked-dir))))
                    ((symbol-function 'read-directory-name)
                     (lambda (&rest _args)
                       (setq prompted t)
                       picked-dir))
                    ((symbol-function 'majjic-log-refresh)
                     (lambda ()
                       (setq opened-root majjic--repo-root)
                       (setq opened-default-directory default-directory)))
                    ((symbol-function 'pop-to-buffer) #'ignore))
            (majjic))
          (should prompted)
          (should (equal opened-root picked-dir))
          (should (equal opened-default-directory picked-dir))
          (should (get-buffer buffer-name)))
      (when-let* ((buffer (get-buffer buffer-name)))
        (kill-buffer buffer))
      (delete-directory start-dir t)
      (delete-directory picked-dir t))))

(ert-deftest majjic-test-effective-undo-preview-skips-synthetic-undo-tip ()
  "A second undo preview should describe the underlying operation, not the top undo op."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-undo-preview-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (jj "new")
      (jj "describe" "-m" "two")
      (jj "undo" "--quiet")
      (let* ((majjic--repo-root repo)
             (preview (majjic--effective-undo-operation-preview)))
        (should (string-match-p "Will undo operation:" preview))
        (should (string-match-p "args: jj new" preview))
        (should-not (string-match-p "Will restore to operation:" preview))
        (should-not (string-match-p "Will undo operation:\n@  [^\n]+\n│  undo: restore to operation" preview))))))

(ert-deftest majjic-test-effective-redo-preview-shows-underlying-operation ()
  "A first redo after two undos should describe the real operation being redone."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-redo-preview-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (jj "new")
      (jj "describe" "-m" "two")
      (jj "new")
      (jj "describe" "-m" "three")
      (jj "undo" "--quiet")
      (jj "undo" "--quiet")
      (let* ((majjic--repo-root repo)
             (preview (majjic--effective-redo-operation-preview)))
        (should (string-match-p "Will redo operation:" preview))
        (should (string-match-p "args: jj new" preview))
        (should-not (string-match-p "Will restore to operation:" preview))
        (should-not (string-match-p "\n│  \\(?:undo\\|redo\\): restore to operation" preview))))))

(ert-deftest majjic-test-undo-cancel-does-not-mutate ()
  "Declining undo confirmation should skip the mutation runner."
  (let ((majjic--repo-root "/tmp")
        (called nil))
    (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
               (lambda (_action) nil))
              ((symbol-function 'majjic--run-mutation)
               (lambda (&rest _args) (setq called t))))
      (majjic-undo))
    (should-not called)))

(ert-deftest majjic-test-rebase-mode-preview-and-cancel ()
  "Entering rebase mode should show transient overlays and cancel should clear them."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (goto-char (point-min))
      (should (search-forward "Edit notes in two distant hunks" nil t))
      (beginning-of-line)
      (let ((source (majjic--current-commit-id)))
        (majjic-rebase-start)
        (should majjic-rebase-mode)
        (should (eq (majjic-rebase-state-source-mode majjic--rebase-state) 'revision))
        (should (equal (majjic-rebase-state-source-change-id majjic--rebase-state)
                       (majjic--change-id-for-commit-id source)))
        (let* ((revision (majjic--current-revision-section))
               (marker-overlay (seq-find (lambda (overlay)
                                           (let ((text (overlay-get overlay 'before-string)))
                                             (and (overlay-start overlay)
                                                  (stringp text)
                                                  (string-match-p "<< move >>" text))))
                                         majjic--rebase-overlays)))
          (should marker-overlay)
          (should (= (overlay-start marker-overlay)
                     (majjic--revision-marker-position revision))))
        (let* ((marker-overlay (seq-find (lambda (overlay)
                                           (let ((text (overlay-get overlay 'before-string)))
                                             (and (stringp text)
                                                  (string-match-p "<< move >>" text))))
                                         majjic--rebase-overlays))
               (marker-text (overlay-get marker-overlay 'before-string)))
          (should (equal (get-text-property 0 'face marker-text)
                         '(:inherit (shadow magit-section-highlight) :weight bold))))
        (goto-char (point-min))
        (should (search-forward "Remove fallback name assignment" nil t))
        (beginning-of-line)
        (majjic--sync-rebase-overlays)
        (should (seq-some (lambda (overlay)
                            (let ((text (or (overlay-get overlay 'before-string)
                                            (overlay-get overlay 'after-string))))
                              (and (overlay-start overlay)
                                   (stringp text)
                                   (string-match-p "<< onto >>" text))))
                          majjic--rebase-overlays))
        (let* ((onto-overlay (seq-find (lambda (overlay)
                                         (let ((text (overlay-get overlay 'before-string)))
                                           (and (stringp text)
                                                (string-match-p "<< onto >>" text))))
                                       majjic--rebase-overlays))
               (onto-text (overlay-get onto-overlay 'before-string))
               (target-section (majjic--current-revision-section))
               (target-change-id (oref target-section change-id))
               (target-commit-id (oref target-section value)))
          (should (string-match-p "<< onto >>" onto-text))
          (should (equal (get-text-property 0 'face onto-text) 'default))
          (should (equal (get-text-property (string-match "<<" onto-text) 'face onto-text)
                         '(:inherit shadow :weight bold)))
          (should (string-match-p (regexp-quote (majjic--short-id target-change-id)) onto-text))
          (should-not (string-match-p (regexp-quote (majjic--short-id target-commit-id)) onto-text)))
        (majjic-abandon-start)
        (should (eq (majjic-rebase-state-target-mode majjic--rebase-state) 'after))
        (majjic-rebase-set-source-descendants)
        (should (eq (majjic-rebase-state-source-mode majjic--rebase-state) 'descendants))
        (should (seq-some (lambda (overlay)
                            (let ((text (or (overlay-get overlay 'before-string)
                                            (overlay-get overlay 'after-string))))
                              (and (stringp text)
                                   (string-match-p "itself and descendants of" text))))
                          majjic--rebase-overlays))
        (majjic-rebase-start)
        (should (eq (majjic-rebase-state-source-mode majjic--rebase-state) 'revision))
        (should (= (seq-count (lambda (overlay)
                                (let ((text (overlay-get overlay 'before-string)))
                                  (and (stringp text)
                                       (string-match-p "<< move >>" text))))
                              majjic--rebase-overlays)
                 1))
        (when-let* ((target (majjic--current-revision-section))
                    (next (majjic--next-top-level-section target)))
          (should (majjic--previous-top-level-section next))
          (should (equal (majjic--rebase-target-summary-prefix target 'before)
                         (majjic--rebase-target-summary-prefix next 'after))))
        (majjic-rebase-set-before)
        (majjic-toggle-at-point)
        (let* ((target (majjic--current-revision-section))
               (before-overlay (seq-find (lambda (overlay)
                                           (let ((text (overlay-get overlay 'after-string)))
                                             (and (overlay-start overlay)
                                                  (stringp text)
                                                  (string-match-p "<< before >>" text))))
                                         majjic--rebase-overlays)))
          (should before-overlay)
          (should (> (overlay-start before-overlay)
                     (oref target content))))
        (let ((called nil))
          (cl-letf (((symbol-function 'majjic--run-mutation)
                     (lambda (&rest _args) (setq called t))))
            (majjic--goto-commit source)
            (should-error (majjic-rebase-apply) :type 'user-error)
            (should-not called)))
        (majjic-rebase-cancel)
        (should-not majjic-rebase-mode)
        (should-not majjic--rebase-state)
        (should-not majjic--rebase-overlays)))))

(ert-deftest majjic-test-rebase-apply-moves-source-and-keeps-it-selected ()
  "Applying rebase in the UI should move the source and keep it selected."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-rebase-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "root\n"))
      (jj "describe" "-m" "root")
      (let ((root (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id")))
        (jj "new")
        (with-temp-file (expand-file-name "f.txt" repo)
          (insert "child\n"))
        (jj "describe" "-m" "child")
        (let* ((_child (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id"))
               (child-change (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "change_id")))
          (jj "new" root)
          (with-temp-file (expand-file-name "g.txt" repo)
            (insert "side\n"))
          (jj "describe" "-m" "side")
          (let ((side (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id")))
            (majjic)
            (with-current-buffer (majjic--log-buffer-name repo)
              (goto-char (point-min))
              (should (search-forward "child" nil t))
              (beginning-of-line)
              (majjic-rebase-start)
              (goto-char (point-min))
              (should (search-forward "side" nil t))
              (beginning-of-line)
              (majjic-rebase-apply)
              (should (equal (majjic--change-id-for-commit-id (majjic--current-commit-id))
                             child-change))
              (should-not majjic-rebase-mode)
              (should (equal (jj "log" "-r" (format "parents(%s)" (majjic--current-commit-id))
                                 "--no-graph" "--color" "never" "--template" "commit_id")
                             side)))))))))

(ert-deftest majjic-test-rebase-descendants-apply-and-reject-internal-target ()
  "Descendants source mode should move the subtree and reject targets inside it."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-rebase-descendants-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "root\n"))
      (jj "describe" "-m" "root")
      (let ((root (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id")))
        (jj "new")
        (with-temp-file (expand-file-name "f.txt" repo)
          (insert "child\n"))
        (jj "describe" "-m" "child")
        (let ((child (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id"))
              (child-change (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "change_id")))
          (jj "new")
          (with-temp-file (expand-file-name "f.txt" repo)
            (insert "grandchild\n"))
          (jj "describe" "-m" "grandchild")
          (let ((grandchild-change (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "change_id")))
            (jj "new" root)
            (with-temp-file (expand-file-name "g.txt" repo)
              (insert "side\n"))
            (jj "describe" "-m" "side")
            (let ((side (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id")))
              (majjic)
              (with-current-buffer (majjic--log-buffer-name repo)
                (majjic--goto-commit child)
                (majjic-rebase-start)
                (majjic-rebase-set-source-descendants)
                (goto-char (point-min))
                (should (search-forward "grandchild" nil t))
                (beginning-of-line)
                (should-error (majjic-rebase-apply) :type 'user-error)
                (should majjic-rebase-mode)
                (should majjic--rebase-overlays)
                (goto-char (point-min))
                (should (search-forward "side" nil t))
                (beginning-of-line)
                (majjic-rebase-apply)
                (should-not majjic-rebase-mode)
                (let* ((rebased-child (majjic--commit-id-for-change-id child-change))
                       (rebased-grandchild (majjic--commit-id-for-change-id grandchild-change)))
                  (should (equal (jj "log" "-r" (format "parents(%s)" rebased-child)
                                     "--no-graph" "--color" "never" "--template" "commit_id")
                                 side))
                  (should (equal (jj "log" "-r" (format "parents(%s)" rebased-grandchild)
                                     "--no-graph" "--color" "never" "--template" "commit_id")
                                 rebased-child)))))))))))

(ert-deftest majjic-test-undo-redo-roundtrip ()
  "Undo and redo should roundtrip a simple repository mutation through the UI."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-undo-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (let ((first (jj "log" "-r" "@" "--no-graph" "--color" "never"
                       "--template" "commit_id")))
        (majjic)
        (with-current-buffer (majjic--log-buffer-name repo)
          (majjic-new)
          (let ((second (jj "log" "-r" "@" "--no-graph" "--color" "never"
                            "--template" "commit_id")))
            (should-not (equal first second))
            (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                       (lambda (_action) t)))
              (majjic-undo))
            (should (equal (jj "log" "-r" "@" "--no-graph" "--color" "never"
                               "--template" "commit_id")
                           first))
            (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                       (lambda (_action) t)))
              (majjic-redo))
            (should (equal (jj "log" "-r" "@" "--no-graph" "--color" "never"
                            "--template" "commit_id")
                           second))))))))

(ert-deftest majjic-test-undo-redo-reselects-rewritten-change ()
  "Undo and redo should keep the same logical change selected across rewrites."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-undo-rewrite-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (let* ((original-commit (jj "log" "-r" "@" "--no-graph" "--color" "never"
                                  "--template" "commit_id"))
             (change-id (jj "log" "-r" "@" "--no-graph" "--color" "never"
                            "--template" "change_id")))
        (jj "describe" "-m" "one updated")
        (let ((rewritten-commit (jj "log" "-r" "@" "--no-graph" "--color" "never"
                                    "--template" "commit_id")))
          (should-not (equal original-commit rewritten-commit))
          (majjic)
          (with-current-buffer (majjic--log-buffer-name repo)
            (goto-char (point-min))
            (should (search-forward "one updated" nil t))
            (beginning-of-line)
            (should (equal (majjic--current-commit-id) rewritten-commit))
            (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                       (lambda (_action) t)))
              (majjic-undo))
            (should (equal (majjic--change-id-for-commit-id (majjic--current-commit-id))
                           change-id))
            (should (equal (majjic--current-commit-id) original-commit))
            (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                       (lambda (_action) t)))
              (majjic-redo))
            (should (equal (majjic--change-id-for-commit-id (majjic--current-commit-id))
                           change-id))
            (should (equal (majjic--current-commit-id) rewritten-commit))))))))

(ert-deftest majjic-test-redo-with-nothing-to-redo-leaves-normal-state ()
  "A failed redo should surface via the mutation path and leave no transient mode active."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-redo-empty-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (majjic)
      (with-current-buffer (majjic--log-buffer-name repo)
        (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                   (lambda (_action) t)))
          (should-not (majjic-redo)))
        (should-not majjic-rebase-mode)
        (should (derived-mode-p 'majjic-log-mode))))))

(provide 'majjic-tests)

;;; majjic-tests.el ends here
