;;; majjic-tests.el --- Lightweight tests for Majjic -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;;; Commentary:

;; Small seam-focused tests for the Majjic refactor.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'majjic)

(defun majjic-test--kill-demo-buffer ()
  "Remove any existing demo log buffer so tests start with clean UI state."
  (when-let* ((buffer (get-buffer "majjic: majjic-demo")))
    (kill-buffer buffer)))

(ert-deftest majjic-test-parse-root-and-trailing-elided ()
  "Root revisions should not synthesize a summary, and trailing `~' survives."
  (let* ((sep majjic--record-separator)
         (output (concat sep "zzzzzzzz" sep "00000000" sep "◆ zzzzzzzz root() 00000000\n"
                         "│\n"
                         "~\n"))
         (records (majjic--parse-log-output output)))
    (should (= (length records) 2))
    (should (eq (majjic-revision-kind (nth 0 records)) 'revision))
    (should-not (majjic-revision-summary (nth 0 records)))
    (should (eq (majjic-revision-kind (nth 1 records)) 'graph))
    (should (equal (majjic-revision-heading (nth 1 records)) "~"))))

(ert-deftest majjic-test-parse-summary-and-multi-hunk-diff ()
  "Summary parsing should preserve rename rows and parse multiple hunks."
  (let* ((changes (majjic--parse-file-summary-output
                   "M app.py\nR {old.txt => new.txt}"))
         (hunks (majjic--parse-file-diff-output
                 (string-join
                  '("diff --git a/app.py b/app.py"
                    "index 1111111..2222222 100644"
                    "--- a/app.py"
                    "+++ b/app.py"
                    "@@ -1,2 +1,2 @@"
                    "-old"
                    "+new"
                    "@@ -10 +10 @@"
                    "-x"
                    "+y")
                  "\n"))))
    (should (= (length changes) 2))
    (should (equal (majjic-file-change-path (nth 0 changes)) "app.py"))
    (should (majjic-file-change-rename (nth 1 changes)))
    (should (= (length hunks) 2))
    (should (= (majjic-hunk-index (nth 0 hunks)) 0))
    (should (= (majjic-hunk-index (nth 1 hunks)) 1))
    (should (= (majjic-hunk-old-start (nth 1 hunks)) 10))
    (should (= (majjic-hunk-new-start (nth 1 hunks)) 10))))

(ert-deftest majjic-test-refresh-preserves-selection-and-expansion ()
  "A rerender should preserve the selected revision and expanded revision state."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (goto-char (point-min))
      (let ((top-prefix (majjic--rebase-target-summary-prefix
                         (majjic--current-revision-section) 'after)))
        (should-not (string-match-p "│" top-prefix)))
      (goto-char (point-min))
      (should (search-forward "Edit notes in two distant hunks" nil t))
      (beginning-of-line)
      (let ((selected (majjic--current-change-id)))
        (majjic-toggle-at-point)
        (should (= (length (majjic--expanded-change-ids)) 1))
        (majjic--log-refresh-sync (majjic--capture-refresh-state))
        (should (equal (majjic--current-change-id) selected))
        (should (= (length (majjic--expanded-change-ids)) 1))))))

(ert-deftest majjic-test-rebase-command-args ()
  "Rebase command args should map target modes to the expected jj flags."
  (should (equal (majjic--rebase-args "src" "dst" 'onto)
                 '("rebase" "-r" "src" "--onto" "dst")))
  (should (equal (majjic--rebase-args "src" "dst" 'after)
                 '("rebase" "-r" "src" "--insert-after" "dst")))
  (should (equal (majjic--rebase-args "src" "dst" 'before)
                 '("rebase" "-r" "src" "--insert-before" "dst"))))

(ert-deftest majjic-test-undo-redo-command-args ()
  "Undo and redo helpers should return the expected jj command shapes."
  (should (equal (majjic--undo-args) '("undo")))
  (should (equal (majjic--redo-args) '("redo")))
  (let ((majjic--repo-root "/tmp")
        (called nil))
    (cl-letf (((symbol-function 'majjic--call-jj)
               (lambda (_dir &rest args)
                 (setq called args)
                 "op-summary\n")))
      (should (equal (majjic--op-log-preview) "op-summary"))
      (should (equal called '("--at-op" "@" "--ignore-working-copy"
                              "op" "log" "-n" "1" "--color" "always"
                              "--no-pager"))))))

(ert-deftest majjic-test-op-preview-buffer-renders-ansi-colors ()
  "The temporary operation preview buffer should render ANSI faces, not escapes."
  (let ((buffer (get-buffer-create "*majjic test preview*")))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'majjic--op-log-preview)
                     (lambda ()
                       "\e[31mred op\e[0m\nplain")))
            (majjic--prepare-op-preview-buffer buffer (majjic--op-log-preview)))
          (with-current-buffer buffer
            (should (equal (buffer-string) "red op\nplain\n"))
            (should-not (string-match-p "\e\\[" (buffer-string)))
            (should (seq-some (lambda (overlay)
                                (overlay-get overlay 'face))
                              (overlays-at (point-min))))))
      (when (buffer-live-p buffer)
        (kill-buffer buffer)))))

(ert-deftest majjic-test-confirm-latest-operation-peek-cleans-up-on-decline ()
  "Declining confirmation should close and kill the temporary side-window peek."
  (save-window-excursion
    (let ((selected (selected-window))
          (display-called nil)
          (original-display (symbol-function 'display-buffer-in-side-window)))
      (unwind-protect
          (progn
            (cl-letf (((symbol-function 'majjic--effective-undo-operation-preview)
                       (lambda ()
                         "@  abc user 1 minute ago\n│  new empty commit"))
                      ((symbol-function 'display-buffer-in-side-window)
                       (lambda (buffer alist)
                         (setq display-called (list buffer alist))
                         (funcall original-display buffer alist)))
                      ((symbol-function 'y-or-n-p)
                       (lambda (_prompt)
                         (should (equal (selected-window) selected))
                         (should (get-buffer-window "*majjic undo preview*"))
                         nil)))
              (should-not (majjic--confirm-latest-operation "undo")))
            (should display-called)
            (should (equal (alist-get 'side (cadr display-called)) 'bottom))
            (should-not (get-buffer "*majjic undo preview*")))
        (when-let* ((buffer (get-buffer "*majjic undo preview*")))
          (kill-buffer buffer))))))

(ert-deftest majjic-test-confirm-latest-operation-peek-cleans-up-on-quit ()
  "`C-g' during confirmation should also clean up the temporary peek."
  (cl-letf (((symbol-function 'majjic--effective-redo-operation-preview)
             (lambda ()
               "@  abc user 1 minute ago\n│  new empty commit"))
            ((symbol-function 'y-or-n-p)
             (lambda (_prompt)
               (keyboard-quit))))
    (let ((quit-seen nil))
      (save-window-excursion
        (condition-case nil
            (majjic--confirm-latest-operation "redo")
          (quit (setq quit-seen t))))
      (should quit-seen))
    (should-not (get-buffer "*majjic redo preview*"))))

(ert-deftest majjic-test-confirm-latest-operation-fetches-preview-in-log-buffer ()
  "Fetching op-log preview should happen before switching to the temporary buffer."
  (with-temp-buffer
    (let ((majjic--repo-root "/repo")
          (called-root nil))
      (cl-letf (((symbol-function 'majjic--effective-undo-operation-preview)
                 (lambda ()
                   (setq called-root majjic--repo-root)
                   "latest op"))
                ((symbol-function 'display-buffer-in-side-window)
                 (lambda (&rest _args)
                   (selected-window)))
                ((symbol-function 'y-or-n-p)
                 (lambda (_prompt) nil)))
        (should-not (majjic--confirm-latest-operation "undo"))
        (should (equal called-root "/repo"))))))

(ert-deftest majjic-test-prompts-for-directory-outside-repo ()
  "Opening `majjic' outside a repo should prompt for a directory first."
  (let* ((start-dir (file-name-as-directory (make-temp-file "majjic-start-" t)))
         (picked-dir (file-name-as-directory (make-temp-file "majjic-picked-" t)))
         (buffer-name (majjic--log-buffer-name picked-dir))
         (prompted nil)
         (opened-root nil)
         (opened-default-directory nil))
    (unwind-protect
        (let ((default-directory start-dir))
          (cl-letf (((symbol-function 'majjic--locate-root)
                     (lambda (dir)
                       (cond
                        ((equal dir start-dir) nil)
                        ((equal dir picked-dir) picked-dir))))
                    ((symbol-function 'read-directory-name)
                     (lambda (&rest _args)
                       (setq prompted t)
                       picked-dir))
                    ((symbol-function 'majjic-log-refresh)
                     (lambda ()
                       (setq opened-root majjic--repo-root)
                       (setq opened-default-directory default-directory)))
                    ((symbol-function 'pop-to-buffer) #'ignore))
            (majjic))
          (should prompted)
          (should (equal opened-root picked-dir))
          (should (equal opened-default-directory picked-dir))
          (should (get-buffer buffer-name)))
      (when-let* ((buffer (get-buffer buffer-name)))
        (kill-buffer buffer))
      (delete-directory start-dir t)
      (delete-directory picked-dir t))))

(ert-deftest majjic-test-effective-undo-preview-skips-synthetic-undo-tip ()
  "A second undo preview should describe the underlying operation, not the top undo op."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-undo-preview-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (jj "new")
      (jj "describe" "-m" "two")
      (jj "undo" "--quiet")
      (let* ((majjic--repo-root repo)
             (preview (majjic--effective-undo-operation-preview)))
        (should (string-match-p "Will undo operation:" preview))
        (should (string-match-p "args: jj new" preview))
        (should-not (string-match-p "Will restore to operation:" preview))
        (should-not (string-match-p "Will undo operation:\n@  [^\n]+\n│  undo: restore to operation" preview))))))

(ert-deftest majjic-test-effective-redo-preview-shows-underlying-operation ()
  "A first redo after two undos should describe the real operation being redone."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-redo-preview-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (jj "new")
      (jj "describe" "-m" "two")
      (jj "new")
      (jj "describe" "-m" "three")
      (jj "undo" "--quiet")
      (jj "undo" "--quiet")
      (let* ((majjic--repo-root repo)
             (preview (majjic--effective-redo-operation-preview)))
        (should (string-match-p "Will redo operation:" preview))
        (should (string-match-p "args: jj new" preview))
        (should-not (string-match-p "Will restore to operation:" preview))
        (should-not (string-match-p "\n│  \\(?:undo\\|redo\\): restore to operation" preview))))))

(ert-deftest majjic-test-undo-cancel-does-not-mutate ()
  "Declining undo confirmation should skip the mutation runner."
  (let ((majjic--repo-root "/tmp")
        (called nil))
    (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
               (lambda (_action) nil))
              ((symbol-function 'majjic--run-mutation)
               (lambda (&rest _args) (setq called t))))
      (majjic-undo))
    (should-not called)))

(ert-deftest majjic-test-rebase-mode-preview-and-cancel ()
  "Entering rebase mode should show transient overlays and cancel should clear them."
  (skip-unless (file-directory-p "/Users/andyphan/code/majjic-demo/.jj"))
  (let ((default-directory "/Users/andyphan/code/majjic-demo/"))
    (majjic-test--kill-demo-buffer)
    (majjic)
    (with-current-buffer "majjic: majjic-demo"
      (goto-char (point-min))
      (should (search-forward "Edit notes in two distant hunks" nil t))
      (beginning-of-line)
      (let ((source (majjic--current-change-id)))
        (majjic-rebase-start)
        (should majjic-rebase-mode)
        (should (equal (majjic-rebase-state-source-change-id majjic--rebase-state)
                       (majjic--change-id-for-commit-id source)))
        (let* ((revision (majjic--current-revision-section))
               (marker-overlay (seq-find (lambda (overlay)
                                           (let ((text (overlay-get overlay 'before-string)))
                                             (and (overlay-start overlay)
                                                  (stringp text)
                                                  (string-match-p "<< move >>" text))))
                                         majjic--rebase-overlays)))
          (should marker-overlay)
          (should (= (overlay-start marker-overlay)
                     (majjic--revision-marker-position revision))))
        (let* ((marker-overlay (seq-find (lambda (overlay)
                                           (let ((text (overlay-get overlay 'before-string)))
                                             (and (stringp text)
                                                  (string-match-p "<< move >>" text))))
                                         majjic--rebase-overlays))
               (marker-text (overlay-get marker-overlay 'before-string)))
          (should (equal (get-text-property 0 'face marker-text)
                         '(:inherit (shadow magit-section-highlight) :weight bold))))
        (majjic-section-forward)
        (should (seq-some (lambda (overlay)
                            (let ((text (or (overlay-get overlay 'before-string)
                                            (overlay-get overlay 'after-string))))
                              (and (overlay-start overlay)
                                   (stringp text)
                                   (string-match-p "<< onto >>" text))))
                          majjic--rebase-overlays))
        (let* ((onto-overlay (seq-find (lambda (overlay)
                                         (let ((text (overlay-get overlay 'before-string)))
                                           (and (stringp text)
                                                (string-match-p "<< onto >>" text))))
                                       majjic--rebase-overlays))
               (onto-text (overlay-get onto-overlay 'before-string)))
          (should (string-match-p "<< onto >>" onto-text))
          (should (equal (get-text-property 0 'face onto-text) 'default))
          (should (equal (get-text-property (string-match "<<" onto-text) 'face onto-text)
                         '(:inherit shadow :weight bold))))
        (majjic-abandon-start)
        (should (eq (majjic-rebase-state-target-mode majjic--rebase-state) 'after))
        (when-let* ((target (majjic--current-revision-section))
                    (next (majjic--next-top-level-section target)))
          (should (majjic--previous-top-level-section next))
          (should (equal (majjic--rebase-target-summary-prefix target 'before)
                         (majjic--rebase-target-summary-prefix next 'after))))
        (majjic-rebase-set-before)
        (majjic-toggle-at-point)
        (let* ((target (majjic--current-revision-section))
               (before-overlay (seq-find (lambda (overlay)
                                           (let ((text (overlay-get overlay 'after-string)))
                                             (and (overlay-start overlay)
                                                  (stringp text)
                                                  (string-match-p "<< before >>" text))))
                                         majjic--rebase-overlays)))
          (should before-overlay)
          (should (> (overlay-start before-overlay)
                     (oref target content))))
        (let ((called nil))
          (cl-letf (((symbol-function 'majjic--run-mutation)
                     (lambda (&rest _args) (setq called t))))
            (majjic--goto-change source)
            (should-error (majjic-rebase-apply) :type 'user-error)
            (should-not called)))
        (majjic-rebase-cancel)
        (should-not majjic-rebase-mode)
        (should-not majjic--rebase-state)
        (should-not majjic--rebase-overlays)))))

(ert-deftest majjic-test-rebase-apply-moves-source-and-keeps-it-selected ()
  "Applying rebase in the UI should move the source and keep it selected."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-rebase-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "root\n"))
      (jj "describe" "-m" "root")
      (let ((root (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id")))
        (jj "new")
        (with-temp-file (expand-file-name "f.txt" repo)
          (insert "child\n"))
        (jj "describe" "-m" "child")
        (let* ((_child (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id"))
               (child-change (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "change_id")))
          (jj "new" root)
          (with-temp-file (expand-file-name "g.txt" repo)
            (insert "side\n"))
          (jj "describe" "-m" "side")
          (let ((side (jj "log" "-r" "@" "--no-graph" "--color" "never" "--template" "commit_id")))
            (majjic)
            (with-current-buffer (majjic--log-buffer-name repo)
              (goto-char (point-min))
              (should (search-forward "child" nil t))
              (beginning-of-line)
              (majjic-rebase-start)
              (goto-char (point-min))
              (should (search-forward "side" nil t))
              (beginning-of-line)
              (majjic-rebase-apply)
              (should (equal (majjic--change-id-for-commit-id (majjic--current-change-id))
                             child-change))
              (should-not majjic-rebase-mode)
              (should (equal (jj "log" "-r" (format "parents(%s)" (majjic--current-change-id))
                                 "--no-graph" "--color" "never" "--template" "commit_id")
                             side)))))))))

(ert-deftest majjic-test-undo-redo-roundtrip ()
  "Undo and redo should roundtrip a simple repository mutation through the UI."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-undo-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (let ((first (jj "log" "-r" "@" "--no-graph" "--color" "never"
                       "--template" "commit_id")))
        (majjic)
        (with-current-buffer (majjic--log-buffer-name repo)
          (majjic-new)
          (let ((second (jj "log" "-r" "@" "--no-graph" "--color" "never"
                            "--template" "commit_id")))
            (should-not (equal first second))
            (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                       (lambda (_action) t)))
              (majjic-undo))
            (should (equal (jj "log" "-r" "@" "--no-graph" "--color" "never"
                               "--template" "commit_id")
                           first))
            (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                       (lambda (_action) t)))
              (majjic-redo))
            (should (equal (jj "log" "-r" "@" "--no-graph" "--color" "never"
                               "--template" "commit_id")
                           second))))))))

(ert-deftest majjic-test-redo-with-nothing-to-redo-leaves-normal-state ()
  "A failed redo should surface via the mutation path and leave no transient mode active."
  (skip-unless (executable-find "jj"))
  (let* ((repo (make-temp-file "majjic-redo-empty-" t))
         (default-directory repo))
    (cl-labels ((jj (&rest args)
                    (let ((default-directory repo))
                      (with-temp-buffer
                        (let ((exit (apply #'process-file "jj" nil t nil args)))
                          (unless (zerop exit)
                            (error "jj %S failed: %s" args (buffer-string)))
                          (string-trim (buffer-string)))))))
      (jj "git" "init" ".")
      (jj "config" "set" "--repo" "user.name" "Test User")
      (jj "config" "set" "--repo" "user.email" "test@example.com")
      (with-temp-file (expand-file-name "f.txt" repo)
        (insert "one\n"))
      (jj "describe" "-m" "one")
      (majjic)
      (with-current-buffer (majjic--log-buffer-name repo)
        (cl-letf (((symbol-function 'majjic--confirm-latest-operation)
                   (lambda (_action) t)))
          (should-not (majjic-redo)))
        (should-not majjic-abandon-mode)
        (should-not majjic-rebase-mode)
        (should (derived-mode-p 'majjic-log-mode))))))

(provide 'majjic-tests)

;;; majjic-tests.el ends here
